version = "0.1"
length_unit = "um"
time_unit = "ms"
diffusion_unit = "um^2/s"

[Cell_Parameters]
cell_space = [[4, 7], [3, 9]] # um
cell_axial_radius = 0.5       # um +/- from 0. Total z range = 2*cell_axial_radius

[Molecule_Parameters]
num_molecules = 1
track_type = "fbm"                                               # "constant", "fbm"
diffusion_coefficient = [0.05, 0.05]                             # um^2/s
diffusion_track_amount = [0.5, 0.5]
hurst_exponent = [0.5]
hurst_track_amount = [1.0]
allow_transition_probability = true
transition_matrix_time_step = 20                                 # ms
diffusion_transition_matrix = [[0.992, 0.008], [0.0273, 0.9727]]
hurst_transition_matrix = [[0.1]]
state_probability_diffusion = [0.5, 0.5]
state_probability_hurst = [1]


[Global_Parameters]
sample_plane_dim = [10, 10] # um
cycle_count = 50
exposure_time = 20          # ms

interval_time = 0          # ms
oversample_motion_time = 1 # ms

[Condensate_Parameters]
initial_centers = [[5, 4, 0], [6, 7, 0]] # um
initial_scale = [0.26, 0.26]             # um
diffusion_coefficient = [0, 0]           # um^2/s
hurst_exponent = [0.2, 0.2]
density_dif = 10

[Output_Parameters]
output_path = "<YOUR-PATH-HERE-CAN-BE-ABSOLUTE-OR-RELATIVE>"
output_name = "Cell_Movie_Test_001"
subsegment_type = "mean"                                     # not implemented yet, use any string
subsegment_number = 5                                        # not implemented yet, use any integer


# PSF Configuration

[psf]
# PSF type: "gaussian"
type = "gaussian"

# If type is "custom", specify the path to the PSF file # not supported currently
custom_path = ""

[psf.parameters]
numerical_aperture = 1.4 # typical range: 0.1 - 1.5
refractive_index = 1.0   # default is air (1.0)

# Multiple Laser Configuration File

[lasers]
active = ["red", "blue"] # List of active lasers provided in setup

[lasers.red]
type = "widefield" # "gaussian" or "hilo" or "widefield"
preset = "red_633"

[lasers.red.parameters]
power = 0.5              # Power in watts 
wavelength = 633         # Wavelength in nanometers
beam_width = 5.0         # 1/e² beam width at waist in microns
numerical_aperture = 1.4 # NA of focusing lens
refractive_index = 1.518
inclination_angle = 67.0 # degrees

[lasers.blue]
type = "widefield"
preset = "blue_405"

[lasers.blue.parameters]
power = 0.5
wavelength = 405
beam_width = 5.0
numerical_aperture = 1.4
refractive_index = 1.518

# Filter Set Configuration
[filters]
filter_set_name = "Red Filter Set"
filter_set_description = "Sample Red filter set configuration"

[filters.excitation]
name = "Red-Ex"
type = "allow_all"
points = 1000

[filters.emission]
name = "Red-Em"
type = "bandpass"
center_wavelength = 600  # nm
bandwidth = 35           # nm
transmission_peak = 0.95
points = 1000

# Camera configurations
[camera]
type = "CMOS"
pixel_count = [200, 200]  # [width, height], 1200x1200 (x pixel_size)
pixel_detector_size = 6.5 # um
magnification = 100
dark_current = 0.0005     # electrons/pixel/second
readout_noise = 1.6       # electrons RMS
bit_depth = 16
sensitivity = 1.0         # electrons/ADU
base_adu = 100            #ADU

# Quantum efficiency curve (wavelength in nm : efficiency 0-1)
# extrapotation for wavelengths not included uses edge values
quantum_efficiency = [
    [
        399,
        0.00,
    ],
    [
        400,
        0.80,
    ],
    [
        500,
        0.90,
    ],
    [
        600,
        0.95,
    ],
    [
        700,
        0.90,
    ],
    [
        800,
        0.70,
    ],
    [
        900,
        0.40,
    ],
    [
        901,
        0.00,
    ],
]

# Fluorophore name
[fluorophore]
name = "PAmCherry"

# States definition
[fluorophore.states.bright]
name = "bright"
state_type = "fluorescent" # any of fluorescent, dark, triplet, bleached

quantum_yield = 0.46 # from 0-1

extinction_coefficient = 18000 # M^-1 cm^-1

fluorescent_lifetime = 0.000000001 # seconds

# Spectral data for bright state
# extrapotation for wavelengths not included uses edge values
[fluorophore.states.bright.excitation_spectrum]
wavelengths = [310.0, 311.0, 411.0, 511.0, 611.0, 612.0]
intensities = [0.00, 0.047, 0.0043, 0.6, 0.06, 0.00]

# extrapotation for wavelengths not included uses edge values
[fluorophore.states.bright.emission_spectrum]
wavelengths = [530.0, 529.0, 600.0, 650.0, 700.0, 797.0, 799.0]
intensities = [0.00, 0.02, 0.98, 0.28, 0.05, 0.003, 0.00]

[fluorophore.states.dark]
name = "dark"
state_type = "dark"

[fluorophore.states.triplet]
name = "triplet"
state_type = "triplet"

[fluorophore.states.bleached]
name = "bleached"
state_type = "bleached"

# State transitions

[fluorophore.transitions.dark_to_bright]
from_state = "dark"
to_state = "bright"
photon_dependent = true
# extrapotation for wavelengths not included uses edge values
[fluorophore.transitions.dark_to_bright.activation_spectrum]
wavelengths = [308.0, 309.0, 359.0, 403.0, 440.0, 484.0, 485.0]
intensities = [0.00, 0.04, 0.11, 1.0, 0.07, 0.0004, 0.00]
activation_extinction_coefficient = 6500                        # M^-1 cm^-1

[fluorophore.transitions.bright_to_dark]
from_state = "bright"
to_state = "dark"
photon_dependent = false
base_rate = 0.1          # 1/s

[fluorophore.transitions.bright_to_bleached]
from_state = "bright"
to_state = "bleached"
photon_dependent = false
base_rate = 0.1          # 1/s

[fluorophore.transitions.bright_to_triplet]
from_state = "bright"
to_state = "triplet"
photon_dependent = false
base_rate = 0.1          # 1/s

[fluorophore.transitions.triplet_to_bleached]
from_state = "triplet"
to_state = "bleached"
photon_dependent = false
base_rate = 0.1          # 1/s

[fluorophore.transitions.triplet_to_dark]
from_state = "triplet"
to_state = "dark"
photon_dependent = false
base_rate = 0.1          # 1/s


[experiment]
name = "PAmCherry_Test"
description = "Sample experiment configuration"
experiment_type = "time-series"                 # "time-series" or "z-stack"
z_position = 0.0
laser_names_active = ["red", "blue"]
laser_powers_active = [0.5, 0.005]              #W
laser_positions_active = [[5, 5, 0], [5, 5, 0]] # um
xyoffset = [0, 0]                               # um

# [experiment.z-stack]
# z_positions = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
# laser_names_active = ["red", "blue"]
# laser_powers_active = [0.005, 0.005] #W
# laser_position_active = [[5,5,0], [5,5,0]] # um
# xyoffset = [0, 0] # um
# exposure_time = 20 # ms, needs to be >= than oversample motion time in GlobalParameters
# interval_time = 0 # ms, must be == 0 or if >0 then must be >= oversample motion time in GlobalParameters

