version = "0.1"
length_unit = "um"
time_unit = "ms"
diffusion_unit = "um^2/s"

[Cell_Parameters]
cell_space = [[4, 7], [3, 9]] # um
cell_axial_radius = 1 # um +/- from 0. Total z range = 2*cell_axial_radius

[Molecule_Parameters]
num_molecules = 1
track_type = "fbm"
diffusion_coefficient = [0.004, 1] # um^2/s
diffusion_track_amount = [0.5, 0.5]
hurst_exponent = [0.5]
hurst_track_amount = [1.0]
allow_transition_probability = true
transition_matrix_time_step = 20 # ms
diffusion_transition_matrix = [[0.992, 0.008], [0.0273, 0.9727]]
hurst_transition_matrix = [[0.1]]
state_probability_diffusion = [0.5, 0.5]
state_probability_hurst = [1]


[Global_Parameters]
sample_plane_dim = [10, 10] # um
frame_count = 500
exposure_time = 100 # ms
interval_time = 0 # ms
oversample_motion_time = 20 # ms

[Condensate_Parameters]
initial_centers = [[5, 4, 0], [6, 7, 0]] # um
initial_scale = [0.26, 0.26] # um
diffusion_coefficient = [0, 0] # um^2/s
hurst_exponent = [0.2, 0.2]
density_dif = 1000

[Output_Parameters]
output_path = "<YOUR-PATH-HERE-CAN-BE-ABSOLUTE-OR-RELATIVE>"
output_name = "Cell_Movie_Test_001"
subsegment_type = "mean"
subsegment_number = 5


# PSF Configuration

[psf]
# PSF type: "airy_disk", "gaussian", "gibson_lanni", "custom"
type = "gaussian"

# If type is "custom", specify the path to the PSF file
custom_path = ""

[psf.parameters]
wavelength = 488.0          # in nanometers
numerical_aperture = 1.4    # typical range: 0.1 - 1.5
z_step = 0.1             # in um
refractive_index = 1.0     # default is air (1.0)

# Multiple Laser Configuration File

[lasers]
active = ["blue", "green", "red"]  # List of active lasers to use

[lasers.blue]
type = "gaussian"  # "gaussian", "flat_top", "donut", "hilo", "hilo_flat_top", "hilo_donut"
preset = "blue_488"  # "blue_488", "green_532", "red_633"

[lasers.blue.parameters]
power = 0.001 # Power in watts (1mW)
wavelength = 488 # Wavelength in nanometers
beam_width = 2.0 # 1/e² beam width at waist in microns
numerical_aperture = 1.4 # NA of focusing lens
refractive_index = 1.518

[lasers.green]
type = "gaussian"
preset = "green_532"

[lasers.green.parameters]
power = 0.002 # Power in watts (2mW)
wavelength = 532 # Wavelength in nanometers
beam_width = 2.0 # 1/e² beam width at waist in microns
numerical_aperture = 1.4 # NA of focusing lens
refractive_index = 1.518

[lasers.red]
type = "gaussian"
preset = "red_633"

[lasers.red.parameters]
power = 0.0005 # Power in watts (0.5mW)
wavelength = 633 # Wavelength in nanometers
beam_width = 2.0 # 1/e² beam width at waist in microns
numerical_aperture = 1.4 # NA of focusing lens
refractive_index = 1.518

# Filter Set Configuration
[filters]
filter_set_name = "FITC Filter Set"
filter_set_description = "Sample FITC filter set configuration"

[filters.excitation]
name = "FITC-Ex"
type = "bandpass"
center_wavelength = 495  # nm
bandwidth = 25  # nm
transmission_peak = 0.95
points = 1000

[filters.emission]
name = "FITC-Em"
type = "bandpass"
center_wavelength = 519  # nm
bandwidth = 35  # nm
transmission_peak = 0.95
points = 1000

[filters.dichroic]
name = "FITC-Di"
type = "tophat"
center_wavelength = 509  # nm
bandwidth = 40  # nm
transmission_peak = 0.95
edge_steepness = 10.0
points = 1000

# Camera configurations
[camera]
type = "CMOS"
pixel_count = [100, 100]  # [width, height], 1200x1200 (x pixel_size)
pixel_detector_size = 6.5 # um
magnification = 100
dark_current = 0.0005  # electrons/pixel/second
readout_noise = 1.6  # electrons RMS
bit_depth = 16
sensitivity = 1.0  # electrons/ADU

# Quantum efficiency curve (wavelength in nm : efficiency 0-1)
quantum_efficiency = [
    [400, 0.80],
    [500, 0.90],
    [600, 0.95],
    [700, 0.90],
    [800, 0.70],
    [900, 0.40]
]

# Fluorophore name
[fluorophore]
name = "Alexa-647"

# States definition
[fluorophore.states.bright]
name = "bright"
state_type = "fluorescent"
quantum_yield = 0.33 # 0-1
extinction_coefficient = 239000 # M^-1 cm^-1
photon_budget = 1000000 # photons

# Spectral data for bright state
[fluorophore.states.bright.excitation_spectrum]
wavelengths = [500.0, 550.0, 600.0, 650.0, 700.0]
intensities = [0.1, 0.3, 0.8, 1.0, 0.4]

[fluorophore.states.bright.emission_spectrum]
wavelengths = [600.0, 650.0, 700.0, 750.0, 800.0]
intensities = [0.2, 0.7, 1.0, 0.6, 0.2]

[fluorophore.states.dark]
name = "dark"
state_type = "dark"

# State transitions
[fluorophore.transitions.bright_to_dark]
from_state = "bright"
to_state = "dark"
rate = 0.1 # 1/s
is_photon_dependent = true

[fluorophore.transitions.dark_to_bright]
from_state = "dark"
to_state = "bright"
rate = 0.05 # 1/s
is_photon_dependent = false